### ISSUE TITLE
issue when running gz-sim after exporting YARP_CLOCK environment variable

### ISSUE THREAD

**Issue by LoreMoretti** [robotology/gz-sim-yarp-plugins#182]
I started `yarpserver` and run `gz sim ergocubGazevoV1_1_gz_sim_world.sdf`, what I get is the following:

![image](https://github.com/user-attachments/assets/9a273ff5-c298-4ed9-b9ed-8e87770ddd59)

The gz-sim window remains black, and the following gets printed:

```
[INFO] |yarp.os.Port|/IITICUBLAP226/gz/62301/clock:i| Port /IITICUBLAP226/gz/62301/clock:i active at tcp://172.20.10.5:10002/
[INFO] |yarp.os.Network| Success: port-to-port persistent connection added.
[ERROR] |yarp.os.NetworkClock| Cannot find time port "/clock" or a time topic "/clock@"
[INFO] |yarp.os.Time| Waiting for clock server to start broadcasting data ...
[INFO] |yarp.os.Time| Waiting for clock server to start broadcasting data ...
```

with this line `[INFO] |yarp.os.Time| Waiting for clock server to start broadcasting data ...` being repeatedly printed on the terminal.

**Comment by traversaro** [comment]
I guess this is the same issue of https://github.com/robotology/gazebo-yarp-plugins/issues/526 that was fixed for Gazebo Classic in https://github.com/robotology/gazebo-yarp-plugins/pull/537, probably we can do a similar fix and a test similar to https://github.com/robotology/gazebo-yarp-plugins/pull/537 ?
