### ISSUE TITLE
Refresh CMake and C++ knowledge (xela-95 version)

### ISSUE THREAD

**Issue by traversaro** [robotology/gz-sim-yarp-plugins#46]
Material:
* https://github.com/ami-iit/ami-commons/wiki/Get-familiar-with-CMake
* https://github.com/ami-iit/ami-commons/wiki/Get-familiar-with-Cxx

**Comment by xela-95** [comment]
@traversaro can assign this issue to me?

**Comment by traversaro** [comment]
Done!

**Comment by traversaro** [comment]
(You should now have permission to assign issues yourself)

**Comment by xela-95** [comment]
> (You should now have permission to assign issues yourself)

I confirm, thanks!

**Comment by traversaro** [comment]
> I gained the base knowledge to needed to start working with gazebo and yarp.
> 
> Useful resources I used:
> 
>     * **[Accelerated C++: Practical Programming by Example](https://www.amazon.com/Accelerated-C-Practical-Programming-Example/dp/020170353X)** by Andrew Koenig and Barbara Moo (old book but one of the best I've read about programming and with a really steep learning curve) - available in lab;
> 
>     * **[C++ Crash Course: A Fast-Paced Introduction](https://amzn.eu/d/9Gkot12)** (I've just started reading this but this is referenced as one of the best books about Modern C++(17), a new edition is coming in 2025 to integrate also C++20);
> 
>     * **[Modern C++ (Lecture & Tutorials, 2020, Vizzo & Stachniss)](https://youtube.com/playlist?list=PLgnQpQtFTOGRM59sr3nSL8BmeMZR9GCIA&si=VomlEz8J1gjEtvnI)** suggested by @LoreMoretti (great video lectures from Bonn University)
> 
>     * **[CMake tutorial](https://cmake.org/cmake/help/latest/guide/tutorial/index.html)** (official tutorial about CMake)
> 
> 
> I think this issue can be closed.

Probably we can add these to https://github.com/ami-iit/ami-commons/wiki/Get-familiar-with-Git .

**Comment by xela-95** [comment]
> Probably we can add these to https://github.com/ami-iit/ami-commons/wiki/Get-familiar-with-Cxx .

Sure! I will open a PR

**Comment by traversaro** [comment]
> > Probably we can add these to https://github.com/ami-iit/ami-commons/wiki/Get-familiar-with-Cxx .
> 
> Sure! I will open a PR

(Unfortunatly) that is a wiki, so you need to directly edit it. Go ahead!
