### ISSUE TITLE
Rename robotinterface singleton with clear name

### ISSUE THREAD

**Issue by traversaro** [robotology/gz-sim-yarp-plugins#69]
Lines like:
~~~
Handler::getHandler()->setDevice(m_deviceScopedName, &m_baseStateDriver)
~~~

are quite confusing, as they do not refer anywhere the robotinterface plugin. We should rename this to make this lines clear.

**Comment by xela-95** [comment]
@traversaro what do you think of
```cpp
RobotInterfaceSingleton::getHandler()->setDevice(m_deviceScopedName, &m_baseStateDriver)
```
?

**Comment by traversaro** [comment]
Thanks! Sorry I was in a meeting, I commented directly in the PR.
