### ISSUE TITLE
Perform walking on new Gazebo

### ISSUE THREAD

**Issue by xela-95** [robotology/gz-sim-yarp-plugins#94]
This epic will track the progress towards the goal of performing walking using [walking-controllers](https://github.com/ami-iit/walking-controllers) in the new Gazebo simulation environment, hence using also [gz-sim-yarp-plugins](https://github.com/robotology/gz-sim-yarp-plugins).

The issue contained in this epic mark the critical path of functionalities needed to make the walking controller work.

CC @traversaro

**Comment by traversaro** [comment]
cc @DanielePucci
